spring:
  main:
    web-application-type: none
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
  security:
     oauth2:
       client:
         registration:
           cli-registration:
             client-id: "poc-java-client-test"
             authorization-grant-type: "code"
             provider: spring-auth-server
             scope: ["openid", "profile"]
         provider:
           spring-auth-server:
             issuer-uri: "http://localhost:9000"
logging:
  file:
    path: target/spring-shell.log
poc:
  java:
    oauth:
      restclient:
        registration:
          id: cli-registration