server:
  port: 9000

logging:
  level:
    org.springframework.security: trace

spring:
  security:
    user:
      name: owner_user
      password: owner_password
      roles: READ
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "poc-java-client-test"
              client-secret: "{noop}pocjavaclientverysecret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "client_credentials"
              redirect-uris:
                - "http://127.0.0.1:11111/fake"
              post-logout-redirect-uris:
                - "http://127.0.0.1:8080/"
              scopes:
                - "openid"
                - "profile"
            require-authorization-consent: true
